#!/bin/bash

LINK="ln -F -f -v -s"
DIR="$( cd "$( dirname "$0" )" && pwd )"

# OSX
$LINK $DIR/osx $HOME/.osx

# Ack
$LINK $DIR/ $HOME/.ackrc

# Shells
$LINK $DIR/zsh/zshenv $HOME/.zshenv
$LINK $DIR/zsh/zshrc $HOME/.zshrc
$LINK $DIR/zsh/zlogin $HOME/.zlogin
$LINK $DIR/bash/bashrc $HOME/.bashrc
$LINK $DIR/bash/bash_login $HOME/.bash_login
$LINK $DIR/tmux/tmux.conf $HOME/.tmux.conf

# Ruby
$LINK $DIR/ruby/irbrc $HOME/.irbrc
$LINK $DIR/ruby/gemrc $HOME/.gemrc
$LINK $DIR/ruby/rdebugrc $HOME/.rdebugrc
$LINK $DIR/ruby/default-gems $HOME/.rbenv/default-gems
$LINK $DIR/ruby/pryrc $HOME/.pryrc

# Git
$LINK $DIR/git/gitconfig $HOME/.gitconfig
$LINK $DIR/git/gitignore_global $HOME/.gitignore_global
