#!/bin/bash

## Variables
LINK="ln -s -F -f -v"

## Actions

# OSX
LINK .osl $HOME/.osx

# Shells
LINK .zshenv $HOME/.zshenv
LINK .zshrc $HOME/.zshrc
LINK .zlogin $HOME/.zlogin
LINK .bashrc $HOME/.bashrc
LINK .bash_login $HOME/.bash_login
LINK .tmux.conf $HOME/.tmux.conf

# Ruby
LINK .irbrc $HOME/.irbrc
LINK .gemrc $HOME/.gemrc
LINK .rdebugrc $HOME/.rdebugrc
LINK .rvmrc $HOME/.rvmrc

# Git
LINK .gitconfig $HOME/.gitconfig
LINK .gitignore_global $HOME/.gitignore_global
