export PATH=~/src/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# For jsctags
export PATH=/usr/local/lib/jsctags:$PATH

export PATH=/opt/subversion/bin:$PATH
# For OpenSSL
export PATH=/usr/local/opt/openssl/bin:$PATH
# Go
GOPATH=$HOME/src/gocode
export GOPATH
export PATH=$GOPATH/bin:$PATH
export PATH=/usr/local/opt/go/libexec/bin:$PATH
# For rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# For Spacemacs
export PATH=~/.local/bin:$PATH
