# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
ZSH_THEME="norm"
#ZSH_THEME="miloshadzic"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
 COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(rails3 bundler gem git svn)

source $ZSH/oh-my-zsh.sh

export HISTCONTROL=ignoredups

# Customize to your needs...
export PATH=/usr/local/sbin:/opt/local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Make things shorter and better
alias ll='ls -halG'
alias cl="clear"

# Git shortcuts
alias gd='git diff'
alias gdc='git diff --cached'
alias gdt='git difftool'
alias gdtc='git difftool --cached'
alias ghist='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias gac='git apply --check'

# Ruby/Rails shortcuts
alias be='bundle exec'
alias berake='bundle exec rake'
alias becon='bundle exec rails console'
alias berails='bundle exec rails server'

# For Cucumber
alias cuke='bundle exec cucumber'

# For Node.js
export PATH=/usr/local/share/npm/bin:$PATH

# For jsctags
export PATH=/usr/local/lib/jsctags:$PATH

# For Ruby
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_FREE_MIN=500000
export RUBY_HEAP_MIN_SLOTS=40000

# For Postgres
alias pg_start='nohup postgres >logfile 2>&1 </dev/null &'
alias pg_stop='pkill -o postgres'

# For Subversion
export PATH=/opt/subversion/bin:$PATH
SVN_EDITOR=vim
export SVN_EDITOR
alias sdg='svn diff --git'

# For Ackrc
ACKRC='$HOME/.ackrc'
export ACKRC

# For rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# For zeus
alias zc='zeus console'
alias zs='zeus server'
alias zr='zeus rake'

# Vim all the things!
EDITOR=vim
export EDITOR
#set -o vi

# Vi mode key bindings
bindkey "^R" history-incremental-search-backward

# Tmux in Technicolor!
#alias tmux="TERM=screen-256color-bce tmux"
#alias tmux="TERM=xterm-256color tmux"

# rsync
alias synk="rsync -avz -e ssh"

# grep
alias gerp="grep"

# Coupa specific things
source $HOME/.couparc

alias truecrypt='/Applications/TrueCrypt.app/Contents/MacOS/Truecrypt --text'

# Growl the Cloud!
AMZN="-R23053:localhost:23053 aws"
export AMZN
