# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell" #"agnoster" "norm" "miloshadzic"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
 COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(rails brew bundler gem git git-extras svn jira npm redis-cli tmuxinator zeus)

source $ZSH/oh-my-zsh.sh

export HISTCONTROL=ignoredups

# Disable hostname completion
zstyle ':completion:*' hosts off

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Homebrew
alias 'brew installed'=brew list
# Make things shorter and better
alias ll='ls -halG'
alias cl="clear"

# Git shortcuts
alias gd='git diff'
alias gdc='git diff --cached'
alias gdt='git difftool'
alias gdtc='git difftool --cached'
alias ghist='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias gac='git apply --check'
alias sourcetree='stree'

# Ruby/Rails shortcuts
alias be='bundle exec'
alias berake='bundle exec rake'
alias becon='bundle exec rails console'
alias berails='bundle exec rails server'
binstubs='bundle install --jobs 4 --full-index --retry 3 --binstubs .bundle/bin'
export binstubs
alias binstubs=$binstubs
alias binstall='bundle install -j4'

# For Cucumber
alias cuke='bundle exec cucumber'

# Node.js
#export PATH=/usr/local/lib/node_modules/npm/:$PATH
#export PATH=/usr/local/share/npm/bin:$PATH
alias npml='npm link'
alias npmg='npm install --global'
alias npmd='npm install --save-dev'
alias lifts='sails lift' # For sails.js
#alias grunt='nocorrect grunt'

# For jsctags
export PATH=/usr/local/lib/jsctags:$PATH

# For Ruby
#export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_GC_HEAP_INIT_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=100000000
export RUBY_HEAP_FREE_MIN=500000
#export RUBY_FREE_MIN=500000
export RUBY_GC_HEAP_FREE_SLOTS=500000

# For Postgres
alias pg_start='nohup postgres >logfile 2>&1 </dev/null &'
alias pg_stop='pkill -o postgres'

# For Subversion
export PATH=/opt/subversion/bin:$PATH
SVN_EDITOR=vim
export SVN_EDITOR
alias sdg='svn diff --git'

# For search tools
alias gerp="grep"
alias grep='ag'
alias ack='ag'
#ACKRC='$HOME/.ackrc'
#export ACKRC

# For rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Vim all the things!
EDITOR=vim
export EDITOR
#set -o vi

# Vi mode key bindings
bindkey "^R" history-incremental-search-backward

# Tmux in Technicolor!
#alias tmux="TERM=screen-256color-bce tmux"
#alias tmux="TERM=xterm-256color tmux"
source $HOME/src/dotfiles/tmux/tmuxinator/completion/tmuxinator.zsh

# rsync
alias synk="rsync -avzP --progress -e ssh"


# Coupa specific things
source $HOME/.couparc

# Encryption
alias truecrypt='/Applications/TrueCrypt.app/Contents/MacOS/Truecrypt --text'
alias gpg='gpg2'

# Growl the Cloud!
#AMZN="-R23053:localhost:23053 aws"
#export AMZN

