# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell" #"agnoster" "norm" "miloshadzic"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

DISABLE_UPDATE_PROMPT=true

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
 COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins+=(zsh-completions rails brew bundler gem git git-extras svn npm redis-cli tmxu tmuxinator zeus adb encode64 extract)

source $ZSH/oh-my-zsh.sh

fpath=(/usr/local/share/zsh-completions $fpath)

autoload -U compinit && compinit
export HISTCONTROL=ignoredups

# Disable hostname completion
zstyle ':completion:*' hosts off

# Set locale
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Customize to your needs...
#export PATH=~/src/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Compilation
export CC="clang"
export CXX="clang++"
export CFLAGS="-march=native -Os"

# Homebrew
alias 'brew installed'=brew list
alias 'brew purge'=brew cleanup
alias 'brew autoclean'=brew cleanup

# Make things shorter and better
alias ll='ls -halG'
alias cl="clear"

# Git shortcuts
alias gd='git diff'
alias gdc='git diff --cached'
alias gdt='git difftool'
alias gdtc='git difftool --cached'
alias gac='git apply --check'
alias ghist='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias sourcetree='stree'
current_branch='git rev-parse --abbrev-ref HEAD'
export current_branch
alias current_branch=$current_branch
alias gst='git status -sb'
alias merged='git merged'
alias getch='git fetch --tags -p upstream'

# Ruby/Rails shortcuts
alias be='bundle exec'
alias berake='bundle exec rake'
alias becon='bundle exec rails console'
alias berails='bundle exec rails server'
binstubs='bundle check || bundle install --jobs 4 --full-index --retry 3 --binstubs .bundle/bin'
export binstubs
alias binstubs=$binstubs
alias binstall='bundle check || bundle install -j4'
alias zues='zeus'

# For Cucumber
alias cuke='bundle exec cucumber'

# Node.js
#export PATH=/usr/local/lib/node_modules/npm/:$PATH
#export PATH=/usr/local/share/npm/bin:$PATH
alias npml='npm link'
alias npmg='npm install --global'
alias npmd='npm install --save-dev'
alias lifts='sails lift' # For sails.js
#alias grunt='nocorrect grunt'

# For jsctags
#export PATH=/usr/local/lib/jsctags:$PATH

# For OpenSSL
#export PATH=/usr/local/opt/openssl/bin:$PATH

# For Ruby
export RUBY_HEAP_FREE_MIN=500000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_HEAP_INIT_SLOTS=1000000
export RUBY_GC_HEAP_FREE_SLOTS=500000
export RUBY_GC_MALLOC_LIMIT=100000000
export GUARD_GEM_SILENCE_DEPRECATIONS=1

# For Postgres
alias pg_start='nohup postgres >logfile 2>&1 </dev/null &'
alias pg_stop='pkill -o postgres'

# For Subversion
#export PATH=/opt/subversion/bin:$PATH
SVN_EDITOR=vim
export SVN_EDITOR
alias sdg='svn diff --git'

# For search tools
alias gerp="grep"
alias grep='ag'
alias ack='ag'
alias pgerp='pgrep'
#ACKRC='$HOME/.ackrc'
#export ACKRC

# Vim all the things!
alias vim='nvim'
EDITOR=vim
export EDITOR
#VIMRUNTIME=$(echo /usr/local/Cellar/macvim/*/MacVim.app/Contents/Resources/vim/runtime/)
VIMRUNTIME=$(echo ~/src/neovim/runtime/)
export VIMRUNTIME
#set -o vi

# Vi mode key bindings
bindkey "^R" history-incremental-search-backward

# Emacs
alias emc="emacsclient -nw -a=''"
alias ems='emacs -nw'
alias update_spacemacs='git pull --rebase && git submodule sync && git submodule update'

#alias tmux="TERM=screen-256color-bce tmux"
#alias tmux="TERM=xterm-256color tmux"
#source $HOME/src/dotfiles/tmux/tmuxinator/completion/tmuxinator.zsh

# rsync
alias synk="rsync -avzP --progress -e ssh"


# Coupa specific things
source $HOME/.couparc

# Encryption
#alias truecrypt='/Applications/TrueCrypt.app/Contents/MacOS/Truecrypt --text'
#alias gpg='gpg2'
#export gpg

# Growl the Cloud!
#AMZN="-R23053:localhost:23053 aws"
#export AMZN

# Go
#GOPATH=$HOME/src/gocode
#export GOPATH
#export PATH=$GOPATH/bin:$PATH

# For rbenv
#export PATH="$HOME/.rbenv/bin:$PATH"
#if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


# added by travis gem
[ -f /Users/stephenaghaulor/.travis/travis.sh ] && source /Users/stephenaghaulor/.travis/travis.sh
